import React, { useEffect, useState } from 'react';
import Hero from './components/Hero';
import Navigation from './components/Navigation';
import MinistryCard from './components/MinistryCard';
import { MINISTRY_DATA } from './constants';

const App: React.FC = () => {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) return null;

  return (
    <div className="relative w-full min-h-screen bg-[#f3f4f6]">
      
      {/* Main Content */}
      <div className="relative z-10">
        
        {/* Navigation Overlay */}
        <Navigation />

        {/* Hero Section with Spline 3D */}
        <Hero />
        
        {/* Glassmorphism Main Container */}
        <main className="relative w-full bg-white/60 backdrop-blur-3xl shadow-[0_-10px_40px_rgba(31,38,135,0.1)] rounded-t-[3rem] mt-[-2rem] border-t border-white/40 ring-1 ring-white/30">
            {/* Visual separator/handle */}
            <div className="w-full flex justify-center pt-6 pb-2">
                <div className="w-16 h-1.5 bg-gray-400/30 rounded-full backdrop-blur-sm" />
            </div>

            <div className="flex flex-col">
                {MINISTRY_DATA.map((ministry, index) => (
                <MinistryCard 
                    key={ministry.id} 
                    data={ministry} 
                    index={index} 
                />
                ))}
            </div>

            <footer className="py-16 bg-white/40 border-t border-white/30 backdrop-blur-md">
                <div className="container mx-auto px-6 text-center">
                    <p className="text-gray-900 font-bold mb-2">SAEJUNGANG CHURCH</p>
                    <p className="text-gray-600 text-sm">
                        © 2024 Ministry Administration. All rights reserved.
                    </p>
                    <p className="text-gray-500 text-xs mt-4">
                        Images generated by Gemini 2.5 Flash.
                    </p>
                </div>
            </footer>
        </main>

      </div>
    </div>
  );
};

export default App;